=== gbumps/shiny-dollop/web/CONFIG/Page.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!--
    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/__NAME__
-->

<!-- TODO define your own vocabulary/syntax. Example follows:  -->
<!ELEMENT root (
    startelement, 
    endelement, 
    startelementdetail, 
    endelementdetail,
    pages,
    boy, 
    girl)+>
<!ELEMENT startelement (#PCDATA)>
<!ELEMENT endelement (#PCDATA)>
<!ELEMENT startelementdetail (#PCDATA)>
<!ELEMENT endelementdetail (#PCDATA)>
<!ELEMENT pages (#PCDATA)>
<!ELEMENT boy (#PCDATA)>
<!ELEMENT girl (#PCDATA)>

=== gbumps/shiny-dollop/web/CONFIG/jadinyConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!DOCTYPE root SYSTEM "Page.dtd">
<root>
    <startelement>&lt;div class=&quot;blocklayout &quot;&gt;</startelement>
    <endelement>&lt;div class=&quot;row hidden hidden-pagination&quot;&gt;</endelement>
    <startelementdetail>&lt;div class=&quot;product-container cf&quot;&gt;</startelementdetail>
    <endelementdetail>&lt;div class=&quot;related-products&quot;&gt;</endelementdetail>
    <pages>6</pages>
    <boy>https://jadiny.vn/collections/be-trai?page=</boy>
    <girl>https://jadiny.vn/collections/be-gai?page=</girl>
</root>

=== gbumps/shiny-dollop/web/CONFIG/BluekidsConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!DOCTYPE root SYSTEM "Page.dtd">
<root>
    <startelement>&lt;div class=&quot;product-lists box-product-lists mt15 clearfix row&quot;&gt;</startelement>
    <endelement>&lt;div class=&quot;clearfix loadmore row&quot;&gt;</endelement>
    <startelementdetail>&lt;main class=&quot;padding-top-mobile&quot;&gt;</startelementdetail>
    <endelementdetail>&lt;/main&gt;</endelementdetail>
    <pages>3</pages>
    <boy>http://bluekids.vn/collections/be-trai-4-14?page=</boy>
    <girl>http://bluekids.vn/collections/be-gai-4-14?page=</girl>
</root>
